### ISSUE TITLE
Improve compute_objective performances

### ISSUE THREAD

**Issue by amine-athmani** [scheduling-cc/pyscheduling#77]
This can be done by:

- Inhereting machine in each subproblem
- Defining a function for each subproblem (this can explode, around 48 functions )

**Comment by AminosDz** [comment]
The answer to this might be in decorators, where we can define a code and execute it based on some conditions (constraints and objectives). Therefore we'd define only one meta function that will define the 48 functions we talked about.

check the [dataclass](https://github.com/python/cpython/blob/6da1a2e993c955aa69158871b8c8792cef3094c3/Lib/dataclasses.py) decorator implementation for reference

**Comment by Neburam** [comment]
@AminosDz I think we need to discuss this issue one more time before closing it
